---
    # parameters:
    #
    # common:
    #   service_name
    #   enable_ssl: True|False  - config nginx to use ssl certs
    #   nginx_ssl_dest_dir
    #
    # provision:
    #   local_certs_dir: local dir to copy ssl certs from
    #   service_venv_dir
    #   nginx_access_log_path
    #   nginx_error_log_path
    #   nginx_static_dir
    #   nginx_media_dir
    #
    # config:
    #   webserver_dns
    #
    - include_tasks: install_packages.yml
    - include_tasks: setup_config.yml

