---

    # copy ssl certs
    - include_tasks: install_ssl_certs.yml

    # create sites-available
    # with_ssl is internal to the template; enable_ssl defines if (web) service will use https
    - include_tasks: drop_nginx_config.yml  with_ssl='true'
      when: enable_ssl == 'true'
    - include_tasks: drop_nginx_config.yml  with_ssl='false'

    # disabled default site
    - name: ensure default site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

