---
- hosts: tag_hxarc
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/hxarc_vars.yml

  tasks:
      - name: install python2
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        register: result
        changed_when: "result.stdout != ''"


- hosts: tag_hxarc
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/hxarc_vars.yml

  roles:
      - external/jmcvetta.passwordless_sudo
      - { role: external/nmaekawa.apt, apt_other_packages: "{{ apt_required_packages_hxarc }}" }
      - external/Stouts.users


- hosts: tag_hxarc
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
      - vars/hxarc_vars.yml

  tasks:
      - name: install webapp
        include_role:
            name: webapp_install




