# install scripts for monitoring ec2 instances
#
#
# this playbook requirems awscli locally installed!
# and implies aws = true
#
---

# https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
# https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found/41429731
- hosts: "tag_webserver:&tag_project_{{ service_name }}"
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/hxarc_vars.yml

  tasks:
  - name: install python2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: "tag_webserver:&tag_project_{{ service_name }}"
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/hxarc_vars.yml

  tasks:
      - import_role:
          name: external/Stouts.users
        vars:
            users_enabled: yes
            users_users:
                - name: cloudwatch
                  authorized: []
            users_to_install:
                - cloudwatch

      - import_role:
          name: external/nmaekawa.cloudwatch
        vars:
            cloudwatch_user: cloudwatch



