#
# playbook to add extra-ebs to hxarc server
# -----------------------------------------
#
# it creates a new 16G ebs volume, attaches to the hxarc server
#
---

- hosts: '{{ target_hosts | default("tag_service_hxarc", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  # these vars must be defined in vars/hxarc_vars.yml
  #    ebs_device: "/dev/CHANGEME"
  #    ebs_mountpoint: "/opt/CHANGEME"
  vars_files:
      - vars/hxarc_vars.yml
  handlers:
      - include_tasks: handlers/main.yml

  tasks:
      - name: create extra ebs volume
        become_user: "{{ lookup('env', 'USER') }}"
        delegate_to: localhost
        ec2_vol:
            instance: "{{ hostvars[item].ec2_id }}"
            volume_size: 16
            volume_type: gp2
            device_name: "{{ ebs_device }}"
            state: present
        with_items: "{{ hostvars }}"
        register: ec2_vol
        when: "use_aws"

      - name: print ebs info
        debug:
           msg: "{{ item }}"
        with_items: "{{ ec2_vol.results }}"
        when: "use_aws"

      - name: attach volume
        become_user: "{{ lookup('env', 'USER') }}"
        delegate_to: localhost
        ec2_vol:
            id: "{{ item.volume_id }}"
            instance: "{{ item.invocation.module_args.instance }}"
            device_name: "{{ ebs_device }}"
        with_items: "{{ ec2_vol.results }}"
        when: "use_aws"


