---

    - name: set webserver_dns for prod
      set_fact:
          webserver_dns: "{{ service_name }}.{{ org_dns_domain }}"
      when:
          - enable_ssl == "true"
          - ec2_tag_cluster == "prod"

    - name: set webserver_dns for non-prod
      set_fact:
          webserver_dns: "{{ ec2_tag_cluster }}.{{ service_name }}.{{ org_dns_domain }}"
      when:
          - enable_ssl == "true"
          - ec2_tag_cluster not in ["prod", "vagrant"]

    - name: set webserver_dns for non-ssl
      set_fact:
          webserver_dns: "{{ ec2_public_dns_name }}"
      when:
          - enable_ssl != "true"
          - ec2_tag_cluster not in ["prod", "vagrant"]

    - name: set webserver_dns for non-ssl vagrant
      set_fact:
          webserver_dns: "{{ service_name }}.vm"
      when:
          - ec2_tag_cluster == "vagrant"

    - debug:
        msg: "webserver_dns is {{ webserver_dns }}"

