---
    - name: git | clone repository
      become_user: '{{ service_user }}'
      git:
          repo: '{{ service_git_repo }}'
          update: yes
          clone: yes
          force: yes
          version: '{{ service_git_version }}'
          dest: '{{ service_install_dir }}'

    - name: git | move static content to nginx static dir
      become_user: '{{ service_user }}'
      command: "cp -r {{ service_install_dir }}/{{ service_name }}/static {{ service_static_dir }}/static"
      args:
          creates: "{{ service_static_dir }}/static"
