---
    - name: admin user | flask upgrade
      become_user: "{{ service_user }}"
      shell: >
          export {{ service_name | upper}}_DOTENV_PATH={{ service_dotenv_path }} &&
          export FLASK_APP={{ service_name }}/wsgi.py &&
          . {{ service_venv_dir }}/bin/activate &&
          flask db upgrade
      args:
          chdir: "{{ service_install_dir }}"
      #register: flask_db_upgrade
      #ignore_errors: True

      #- fail:
      #  msg: "error during db migration for service {{ service_name }}: {{ flask_db_upgrade.stdout }}"
      #when:
      #    "flask_db_upgrade.rc != 0"


    - name: admin user | create admin user
      become_user: "{{ service_user }}"
      shell: >
          export {{ service_name | upper}}_DOTENV_PATH={{ service_dotenv_path }} &&
          export FLASK_APP={{ service_name }}/wsgi.py &&
          . {{ service_venv_dir }}/bin/activate &&
          flask create_user
          --usr '{{ service_admin_user }}'
          --pwd '{{ service_admin_password }}'
          --email '{{ service_admin_email }}'
          --is_admin
      args:
          chdir: "{{ service_install_dir }}"
      register: create_user
      ignore_errors: True

    - fail:
        msg: "error creating admin user for service {{ service_name }}: {{ create_user.stdout }}"
      when:
          "create_user.rc != 0 and 'already exitst' not in create_user.stdout"



