---
      - name: venv | create subproc venv
        include_role:
            name: external/nmaekawa.virtualenv
        vars:
            venv_path: "{{ subproc_venv_dir }}"
            venv_user: "{{ subproc_user }}"
            venv_group: "{{ subproc_group }}"
            venv_python_version: 3



