---
      - name: drop subprocess wrapper shell  file
        become_user: "{{ subproc_user }}"
        template:
          src: wrapper.sh.j2
          dest: "{{ subproc_wrapper_path }}"
          owner: "{{ subproc_user }}"
          group: "{{ subproc_group }}"
          mode: 0744
          backup: yes

